##import math
###swallow_limit = 60/3
###print swallow_limit
##perc=1/3
##coco_wt=1450
##macaw_wt=900
##macaw_limit=macaw_wt*perc
##num_macaws=coco_wt/macaw_limit
##math.ceil(num_macaws)
##print num_macaws

##dog_age = 10
##dog_multiplier = 7
##human_age = dog_age * dog_multiplier

##
x_rate=0.65
total_dollars=200
fee=2
total_pounds=(total_dollars-fee)*x_rate
print total_pounds
import math
total_dollars = total_pounds/x_rate - fee
math.ceil(total_dollars)
print total_dollars
